//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLKJ.SYS.WebSQL {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebSQL.WebDBSoap")]
    public interface WebDBSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStrValue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetStrValue(string vSQL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable QueryData(string vSQL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Query", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[][]))]
        TLKJ.SYS.WebSQL.DBResult Query(string cFileList, string cTableName, string cWhereParm, string cOrderBy, int iPageNo, int iPageSize);
        
        // CODEGEN: 参数“ParmList”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlArrayItemAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecSQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[][]))]
        TLKJ.SYS.WebSQL.ExecSQLResponse ExecSQL(TLKJ.SYS.WebSQL.ExecSQLRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3130.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DBResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private int pAGE_COUNTField;
        
        private int rOW_COUNTField;
        
        private int pAGE_SIZEField;
        
        private int pAGE_NOField;
        
        private string messageField;
        
        private System.Data.DataTable dtrowsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PAGE_COUNT {
            get {
                return this.pAGE_COUNTField;
            }
            set {
                this.pAGE_COUNTField = value;
                this.RaisePropertyChanged("PAGE_COUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ROW_COUNT {
            get {
                return this.rOW_COUNTField;
            }
            set {
                this.rOW_COUNTField = value;
                this.RaisePropertyChanged("ROW_COUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int PAGE_SIZE {
            get {
                return this.pAGE_SIZEField;
            }
            set {
                this.pAGE_SIZEField = value;
                this.RaisePropertyChanged("PAGE_SIZE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int PAGE_NO {
            get {
                return this.pAGE_NOField;
            }
            set {
                this.pAGE_NOField = value;
                this.RaisePropertyChanged("PAGE_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.Data.DataTable dtrows {
            get {
                return this.dtrowsField;
            }
            set {
                this.dtrowsField = value;
                this.RaisePropertyChanged("dtrows");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecSQL", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecSQLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] sqls;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfAnyType")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public object[][] ParmList;
        
        public ExecSQLRequest() {
        }
        
        public ExecSQLRequest(string[] sqls, object[][] ParmList) {
            this.sqls = sqls;
            this.ParmList = ParmList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecSQLResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecSQLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ExecSQLResult;
        
        public ExecSQLResponse() {
        }
        
        public ExecSQLResponse(int ExecSQLResult) {
            this.ExecSQLResult = ExecSQLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebDBSoapChannel : TLKJ.SYS.WebSQL.WebDBSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebDBSoapClient : System.ServiceModel.ClientBase<TLKJ.SYS.WebSQL.WebDBSoap>, TLKJ.SYS.WebSQL.WebDBSoap {
        
        public WebDBSoapClient() {
        }
        
        public WebDBSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebDBSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebDBSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebDBSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetStrValue(string vSQL) {
            return base.Channel.GetStrValue(vSQL);
        }
        
        public System.Data.DataTable QueryData(string vSQL) {
            return base.Channel.QueryData(vSQL);
        }
        
        public TLKJ.SYS.WebSQL.DBResult Query(string cFileList, string cTableName, string cWhereParm, string cOrderBy, int iPageNo, int iPageSize) {
            return base.Channel.Query(cFileList, cTableName, cWhereParm, cOrderBy, iPageNo, iPageSize);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TLKJ.SYS.WebSQL.ExecSQLResponse TLKJ.SYS.WebSQL.WebDBSoap.ExecSQL(TLKJ.SYS.WebSQL.ExecSQLRequest request) {
            return base.Channel.ExecSQL(request);
        }
        
        public int ExecSQL(string[] sqls, object[][] ParmList) {
            TLKJ.SYS.WebSQL.ExecSQLRequest inValue = new TLKJ.SYS.WebSQL.ExecSQLRequest();
            inValue.sqls = sqls;
            inValue.ParmList = ParmList;
            TLKJ.SYS.WebSQL.ExecSQLResponse retVal = ((TLKJ.SYS.WebSQL.WebDBSoap)(this)).ExecSQL(inValue);
            return retVal.ExecSQLResult;
        }
    }
}
